[build]
  publish = "public"
  command = "npm run build"
[context.branch-deploy]
  command = "npm build"
[context.branch-deploy.environment]
  NODE_ENV = "development"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
